#!/bin/bash
shopt -s extglob

directory=`pwd`

read -p "Clearing case. Are you sure? (y/N) " -n 1 -r
echo ' '
if ! [[ $REPLY =~ ^[Yy]$ ]]
then
    exit
fi

if [ -d "./constant/polyMesh" ]; then
  cd ./constant/polyMesh
  rm -fr !(blockMeshDict)
  cd $directory
fi

rm -fr *[0-9].[0-9]* [0-9] [1-6]* 2>/dev/null
rm -fr pro* 2>/dev/null
rm -fr postProcessing 2>/dev/null
rm -fr logs 2>/dev/null
rm log.* 2>/dev/null
rm *.foam 2>/dev/null
rm constant/waveDict 2>/dev/null
rm system/elementData 2>/dev/null
