#!/bin/bash

. $WM_PROJECT_DIR/bin/tools/RunFunctions
nProc=$(sed -ne 's/^numberOfSubdomains *\(.*\);/\1/p' system/decomposeParDict)
mkdir logs

# Choice
echo Select a choice:
echo  "(1) Waves and forward current"
echo  "(2) Waves and backward current"
echo  "(3) Forward current only"
echo  "(4) Backward current only"
read -p " " -n 1 -r reply
echo ' '

if ! [[ $reply =~ ^[1234]$ ]]
then
    echo Invalid choice
    exit
fi

echo Preparing 0 folder...
cp -r 0.org 0

# Make choice changes
echo Making case adjustments...
if [ $reply == "1" ];
then
    cp 0/U_forw 0/U
    cp system/setFieldsDict_forw system/setFieldsDict
    cp constant/waveDict_wave_forw constant/waveDict
elif [ $reply == "2" ];
then
    cp 0/U_back 0/U
    cp system/setFieldsDict_back system/setFieldsDict
    cp constant/waveDict_wave_back constant/waveDict
elif [ $reply == "3" ];
then
    cp 0/U_forw 0/U
    cp system/setFieldsDict_forw system/setFieldsDict
    cp constant/waveDict_curr_forw constant/waveDict
elif [ $reply == "4" ];
then
    cp 0/U_back 0/U
    cp system/setFieldsDict_back system/setFieldsDict
    cp constant/waveDict_curr_back constant/waveDict
fi

echo blockMesh meshing...
blockMesh > logs/blockMesh.log

echo snappyHexMesh meshing...
snappyHexMesh -overwrite > logs/snappyHexMesh.log

checkMesh

echo topoSet...
topoSet > logs/topoSet.log

echo Setting the fields...
setFields > logs/setFields.log

echo decomposing...
decomposePar > logs/decomposePar.log

echo Running...
mpirun -np $nProc olaDyMFlow -parallel > logs/olaDyMFlowTurbine.log

echo Reconstructing ...
cd processor0
latestTime="$(ls | grep '^[0-9]\+' | sort -n | tail -n1)"
cd ..
for i in $(seq 0 0.25 $latestTime); do
  reconstructPar -time $i >> logs/reconstructPar.log;
done
rm -fr processor*

touch olaFlowTurbine.foam

echo Simulation complete.
